version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: adchat-db
    environment:
      POSTGRES_DB: adchat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: adchat-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/adchat
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
